---
version: '3'

services:
  redis-db:
      container_name: db
      image: redis:7
      ports:
        - "6379:6379"
      command: --save 1 1
      volumes:
        - ./server/data:/data
      user: "1000:1000"

  server:
    container_name: server
    depends_on:
      - redis-db
    image: kelach/bevo-bud-the-gpt_server:1.0
    # build:
    #   context: ./server/
    #   dockerfile: Dockerfile
    ports:
      - "5000:5000"
  
  client:
    container_name: client
    depends_on:
      - server
    image: kelach/bevo-bud-the-gpt_client:1.0
    # build:
    #   context: ./client/
    #   dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    environment:
      - REDIS_PORT=6379
