---
version: '3'
services:
  redis-db:
      container_name: db
      image: redis:7
      ports:
        - "6379:6379"
      command: --save 1 1
      volumes:
        - ./db-data:/db-data
      user: "1000:1000"

  server:
    container_name: server
    depends_on:
      - redis-db
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
      - REDIS_HOSTNAME=redis-db